# Generated by Django 3.2.6 on 2021-08-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_auto_20210815_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codegist',
            name='topic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
