# Generated by Django 3.2.6 on 2021-08-23 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_site', '0005_auto_20210823_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codegist',
            name='coding_platform',
        ),
        migrations.RemoveField(
            model_name='codegist',
            name='problem_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(default=None, max_length=2500),
        ),
        migrations.AlterField(
            model_name='codegist',
            name='analogy',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='codegist',
            name='code_snippet',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('post_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_site.post')),
            ],
        ),
    ]
